-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgk/hcJKnYM61RCBPQ
txPKLrzdXqVjDclxlpP85H7m/hOgCgYIKoZIzj0DAQehRANCAAQZ2yONL7MPzcqW
6/zyCn2IcweNrJBRpegE20EeodKphOYN9BhQCGFOMdZckmRwbAdHdXLPIeS0YO/y
vjE0gHlD
-----END PRIVATE KEY-----